export const collaborationsLogo = [
    { alt: "NHRD", src: "/apply-now/image/recruiter/logo7.webp" },
    { alt: "DCAL", src: "/apply-now/image/recruiter/logo8.webp" },
    { alt: "AIMS", src: "/apply-now/image/recruiter/logo9.webp" },
    { alt: "COURSERA", src: "/apply-now/image/recruiter/logo10.webp" },
    { alt: "ATAL", src: "/apply-now/image/recruiter/logo11.webp" },
    { alt: "SOI", src: "/apply-now/image/recruiter/logo12.webp" },
    { alt: "AIT", src: "/apply-now/image/recruiter/logo13.webp" },
    { alt: "LSUS", src: "/apply-now/image/recruiter/logo14.webp" },
    { alt: "BFSI", src: "/apply-now/image/recruiter/logo15.webp" },
    { alt: "KATHMANDU", src: "/apply-now/image/recruiter/logo16.webp" },
    { alt: "MAHSA", src: "/apply-now/image/recruiter/logo17.webp" },
    { alt: "DE MONTFORT", src: "/apply-now/image/recruiter/logo18.webp" },
    { alt: "XYZ", src: "/apply-now/image/recruiter/logo19.webp" },
    { alt: "Financial University", src: "/apply-now/image/recruiter/logo20.webp" },
    { alt: "Uniglobe", src: "/apply-now/image/recruiter/logo21.webp" },
    { alt: "Archer", src: "/apply-now/image/recruiter/logo22.webp" },
    { alt: "EY", src: "/apply-now/image/recruiter/logo23.webp" },
    { alt: "CNH", src: "/apply-now/image/recruiter/logo24.webp" },
    { alt: "INFOSYS", src: "/apply-now/image/recruiter/logo25.webp" },
    { alt: "ASHOK", src: "/apply-now/image/recruiter/logo26.webp" },
    { alt: "ANAND", src: "/apply-now/image/recruiter/logo27.webp" },
    { alt: "YESBANK", src: "/apply-now/image/recruiter/logo28.webp" },
    { alt: "PhonePe", src: "/apply-now/image/recruiter/logo29.webp" },
    { alt: "Deloitte", src: "/apply-now/image/recruiter/logo30.webp" },
    { alt: "ACCENTURE", src: "/apply-now/image/recruiter/logo31.webp" },
    { alt: "BOB", src: "/apply-now/image/recruiter/logo32.webp" },
    { alt: "UPGRAD", src: "/apply-now/image/recruiter/logo33.webp" },
    { alt: "DECATHLON", src: "/apply-now/image/recruiter/logo34.webp" },
    { alt: "HDB", src: "/apply-now/image/recruiter/logo35.webp" },
    { alt: "HCL", src: "/apply-now/image/recruiter/logo36.webp" },
    { alt: "KPMG", src: "/apply-now/image/recruiter/logo37.webp" },
    { alt: "IBM", src: "/apply-now/image/recruiter/logo38.webp" },
    { alt: "ITC", src: "/apply-now/image/recruiter/logo39.webp" },
    { alt: "DS GROUP", src: "/apply-now/image/recruiter/logo40.webp" },
    { alt: "HITACHI", src: "/apply-now/image/recruiter/logo41.webp" },
    { alt: "SPARK", src: "/apply-now/image/recruiter/logo42.webp" },
    { alt: "AU", src: "/apply-now/image/recruiter/logo43.webp" },
    { alt: "DELL", src: "/apply-now/image/recruiter/logo44.webp" },
    { alt: "INFOEDGE", src: "/apply-now/image/recruiter/logo45.webp" },
    { alt: "PRISM", src: "/apply-now/image/recruiter/logo46.webp" },
    { alt: "SBI", src: "/apply-now/image/recruiter/logo47.webp" },
    { alt: "SBIOS", src: "/apply-now/image/recruiter/logo48.webp" },
    { alt: "KANSAI", src: "/apply-now/image/recruiter/logo49.webp" },
    { alt: "NAUKRI", src: "/apply-now/image/recruiter/logo50.webp" },
    { alt: "LAKSH", src: "/apply-now/image/recruiter/logo51.webp" },
    { alt: "HDFC", src: "/apply-now/image/recruiter/logo52.webp" },
    { alt: "OLN", src: "/apply-now/image/recruiter/logo53.webp" },
    { alt: "PROPERTY", src: "/apply-now/image/recruiter/logo54.webp" },
    { alt: "ANZ", src: "/apply-now/image/recruiter/logo55.webp" },
    { alt: "KPL", src: "/apply-now/image/recruiter/logo56.webp" },
    { alt: "TEAMC", src: "/apply-now/image/recruiter/logo57.webp" },
    { alt: "KOTAK", src: "/apply-now/image/recruiter/logo58.webp" },
    { alt: "SIMP", src: "/apply-now/image/recruiter/logo59.webp" },
    { alt: "LR", src: "/apply-now/image/recruiter/logo60.webp" },
    { alt: "SIMP", src: "/apply-now/image/recruiter/logo61.webp" },
    { alt: "RADISSON", src: "/apply-now/image/recruiter/logo62.webp" },
    { alt: "KENT", src: "/apply-now/image/recruiter/logo63.webp" },
    { alt: "Lifestyle", src: "/apply-now/image/recruiter/logo64.webp" },
    { alt: "AXIS", src: "/apply-now/image/recruiter/logo65.webp" },
    { alt: "BAJAJ", src: "/apply-now/image/recruiter/logo66.webp" },
    { alt: "DTDC", src: "/apply-now/image/recruiter/logo67.webp" },
    { alt: "TECHGO", src: "/apply-now/image/recruiter/logo68.webp" },
    { alt: "EDU", src: "/apply-now/image/recruiter/logo69.webp" },
    { alt: "LR", src: "/apply-now/image/recruiter/logo70.webp" },
    { alt: "AMAZON", src: "/apply-now/image/recruiter/logo71.webp" },
    { alt: "WIPRO", src: "/apply-now/image/recruiter/logo72.webp" },
    { alt: "CROMA", src: "/apply-now/image/recruiter/logo73.webp" },
    { alt: "BLINKIT", src: "/apply-now/image/recruiter/logo74.webp" },
    { alt: "CAFE", src: "/apply-now/image/recruiter/logo75.webp" },
    { alt: "BERGE", src: "/apply-now/image/recruiter/logo76.webp" },
    { alt: "DABUR", src: "/apply-now/image/recruiter/logo77.webp" },
    { alt: "INDIAMART", src: "/apply-now/image/recruiter/logo78.webp" },
    { alt: "ICICI", src: "/apply-now/image/recruiter/logo79.webp" },
    { alt: "UJJIVAN", src: "/apply-now/image/recruiter/logo80.webp" },
    { alt: "Sheela", src: "/apply-now/image/recruiter/logo81.webp" },
];

export const clubsLogo = [
    { alt: "AIT", src: "/apply-now/image/icons/logo1.webp" },
    { alt: "LSUS", src: "/apply-now/image/icons/logo2.webp" },
    { alt: "BFSI", src: "/apply-now/image/icons/logo3.webp" },
    { alt: "Kathmandu", src: "/apply-now/image/icons/logo4.webp" },
    { alt: "University of Dubai ", src: "/apply-now/image/icons/logo5.webp" },
    { alt: "MAHSA", src: "/apply-now/image/icons/logo6.webp" },
    { alt: "DE MONTFORT", src: "/apply-now/image/icons/logo7.webp" },
    { alt: "POLITEKNIK", src: "/apply-now/image/icons/logo8.webp" },
    { alt: "POLITEKNIK", src: "/apply-now/image/icons/logo9.webp" },
    { alt: "POLITEKNIK", src: "/apply-now/image/icons/logo10.webp" },
];  